-- ============================================================================
-- MILESTONE 4: Alerts Table
-- ============================================================================
-- Stores alerts generated when transactions are flagged as suspicious.
-- Used by fraud investigation team to review potential fraud.
-- ============================================================================

CREATE TABLE IF NOT EXISTS alerts (
    -- Primary key
    id BIGSERIAL PRIMARY KEY,
    
    -- Link to transaction
    transaction_id UUID NOT NULL,
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    -- ========================================================================
    -- SCORING RESULTS
    -- ========================================================================
    score NUMERIC(6,4) NOT NULL,              -- Model probability (0.0000-1.0000)
    threshold NUMERIC(6,4) NOT NULL,          -- Threshold used for decision
    decision TEXT NOT NULL,                   -- APPROVE, REVIEW, BLOCK
    
    -- ========================================================================
    -- EXPLAINABILITY
    -- ========================================================================
    -- Top contributing features for this prediction
    -- Format: [{"feature": "amount", "value": 5000, "contribution": 0.35}, ...]
    top_features JSONB NOT NULL,
    
    -- ========================================================================
    -- MODEL METADATA
    -- ========================================================================
    model_name TEXT NOT NULL,                 -- e.g., "fraud-detector-xgboost"
    model_version TEXT NOT NULL,              -- e.g., "1"
    inference_latency_ms INTEGER,             -- How long scoring took
    
    -- ========================================================================
    -- TRANSACTION SNAPSHOT
    -- ========================================================================
    -- Store key transaction data for quick review without joining
    user_id TEXT NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    channel TEXT,
    country TEXT,
    
    -- ========================================================================
    -- RESOLUTION (filled by fraud team later)
    -- ========================================================================
    resolved_at TIMESTAMPTZ,                  -- When reviewed
    resolution TEXT,                          -- CONFIRMED_FRAUD, FALSE_POSITIVE, PENDING
    resolved_by TEXT,                         -- Who reviewed it
    resolution_notes TEXT,                    -- Any notes
    
    -- ========================================================================
    -- CONSTRAINTS
    -- ========================================================================
    CONSTRAINT chk_decision CHECK (decision IN ('APPROVE', 'REVIEW', 'BLOCK')),
    CONSTRAINT chk_resolution CHECK (resolution IS NULL OR resolution IN ('CONFIRMED_FRAUD', 'FALSE_POSITIVE', 'PENDING', 'ESCALATED'))
);

-- ============================================================================
-- INDEXES
-- ============================================================================

-- For finding unresolved alerts
CREATE INDEX IF NOT EXISTS idx_alerts_unresolved 
    ON alerts(created_at DESC) 
    WHERE resolution IS NULL;

-- For finding alerts by decision type
CREATE INDEX IF NOT EXISTS idx_alerts_decision 
    ON alerts(decision, created_at DESC);

-- For finding high-score alerts
CREATE INDEX IF NOT EXISTS idx_alerts_score 
    ON alerts(score DESC);

-- For finding alerts by user
CREATE INDEX IF NOT EXISTS idx_alerts_user 
    ON alerts(user_id, created_at DESC);

-- For finding alerts by transaction
CREATE INDEX IF NOT EXISTS idx_alerts_txn 
    ON alerts(transaction_id);

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON TABLE alerts IS 
    'Fraud alerts generated by the scoring API for investigation';

COMMENT ON COLUMN alerts.score IS 
    'Model-predicted probability of fraud (0-1)';

COMMENT ON COLUMN alerts.decision IS 
    'APPROVE: Low risk, REVIEW: Manual review needed, BLOCK: High risk auto-blocked';

COMMENT ON COLUMN alerts.top_features IS 
    'JSON array of top contributing features for explainability';
